### ISSUE TITLE
i3 online install xbacklight for brightness control

### ISSUE THREAD

**Issue by bevsxyz** [endeavouros-team/calamares_config_next#2]
The online install missed a package for xbacklight, thereby lacked a way to control the screen backlight. We need to install [acpilight](https://archlinux.org/packages/community/any/acpilight/) community package to change the backlight. Also, we need to add write permission for the sys class file to change the brightness.

**Comment by killajoe** [comment]
acpilight is replacing xorg-xbacklight and not needed in most cases. 
xorg-xbacklight could be added to have some default.
